### ISSUE TITLE
Apply shortcut Ctrl+/ to ToggleLineComment

### ISSUE THREAD

**Issue by justcla** [justcla/KeyBindings#18]
Now that VS2019 has Edit.ToggleLineComment, mappings should be updated to bind Ctrl+/ to Edit.ToggleLineComment.

**Comment by MZengYi** [comment]
not support VS2002?

**Comment by justcla** [comment]
Good pickup. My bad. I'll add that in. Thanks!

**Comment by justcla** [comment]
I fight SO HARD to have that command built into the product. Lol. Since 2015. Now we can finally use it!
(Still doesn't move down one line, though)

**Comment by justcla** [comment]
Also it only applies to C#, so it doesn't work everywhere.

**Comment by justcla** [comment]
Done! Hot Keys extension is updated with "**C# Editor**" scope bindings for ToggleLineComment and ToggleBlockComment.
When not in a C# editor, the commands will do Comment and Uncomment instead.

Check out version [4.1.0 of Hot Keys](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotKeys).
