### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by jasekiw** [justcla/KeyBindings#19]
The installer doesn't give visual studio 2022 as an option to install to.

The extension also isn't searchable in the visual studio extensions panel.

![image](https://user-images.githubusercontent.com/4037224/141359074-cf19737d-eb93-403c-b61f-b7f4ad1c87ff.png)

**Comment by sepharg** [comment]
yes please add VS 2022 support!

**Comment by justcla** [comment]
Please tell me...
Which key bindings are you most interested in?
(I'll try to make sure they use the most recent VS2022 commands.)

**Comment by sepharg** [comment]
In my case I use all of the navigation ones (to go definition, implementation, locate in solution explorer, navigate back and forth, find usages, etc), and also the most common refactoring ones

**Comment by justcla** [comment]
Thanks. But which making scheme? IntelliJ? Resharper?

**Comment by sepharg** [comment]
IntelliJ

**Comment by justcla** [comment]
The easy way is to just import the vssettings file.

**Comment by justcla** [comment]
It is now upgraded for VS2022 and available on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotKeys).
Enjoy!

**Comment by justcla** [comment]
@sepharg - Did the upgraded extension work for you?

**Comment by sepharg** [comment]
thanks @justcla just tried it and works fine with 2022!
