### ISSUE TITLE
Rename key shortcuts is invalid

### ISSUE THREAD

**Issue by rainbowechoes** [justcla/KeyBindings#27]
Hi Justcla,

you create a very useful and wonderful project. but when I used this extension, I met a problem.

I chose the IntelliJ IDEA settings, and the key shortcuts of rename also changed to `Shift + F6`, but when I use this shortcut, it don't work. but the others can work. I don't know why, could you help me?

**Comment by justcla** [comment]
Thanks. I'm glad you like the tool.

I'll investigate why the rename shortcut isn't working.

**Comment by rainbowechoes** [comment]
I also updated my visual studio to the latest version, but I can't input the shortcut keys. like this:
![Uploading image.png…]()

**Comment by justcla** [comment]
To input all the shortcuts for the IntelliJ mapping, load them from the menu items.
Tools->Keyboard Shortcuts-> Load Shortcuts->IntelliJ IDEA
![image](https://github.com/justcla/KeyBindings/assets/17131343/dc92c588-5dcb-497f-a28b-7de4604cfd7e)

You should get a dialog that shows all the shortcuts that will be imported.
![image](https://github.com/justcla/KeyBindings/assets/17131343/3bce54b4-fc88-47a8-a5d8-df22facd642c)

And once you've imported them, you should find them showing in the Settings box (Tools->Options; Environment->Keyboard)

**Comment by rainbowechoes** [comment]
yeah, that's exactly what I did.

but I can't input `Shift` to shortcut keys, but others are OK, like `Esc` or `Ctrl`. very wired.
![image](https://github.com/justcla/KeyBindings/assets/38370475/789bb222-a2d9-43bd-9154-c042b0093b25)

**Comment by justcla** [comment]
I suspect the problem is not with the imported shortcuts. It sounds like you have an issue with the Shift key. Perhaps your keyboard is broken. Maybe the issue is only with SHIFT+(Fnc-keys). Try testing the shift key with other keys, like Shift+A. Try using the shift key inside the editor. Try it outside VS.

If you can't verify the shortcuts in the "Press shortcut keys" box, try using the "Show commands containing" box. Search for "Refactor.Rename" and select the item when it's found. Drop down the "Shortcuts for selected command:" field and you should see "Shift+F6 (Text Editor)"

![image](https://github.com/justcla/KeyBindings/assets/17131343/6216c96d-e263-4d52-8bbf-6f30c4102acf)

**Comment by rainbowechoes** [comment]
I'm sure my SHIFT is OK. I have tested it before.

I used another keyboard, then I found, shortcut key CTRL + ALT + S not work. I don't know why. but now I think maybe it should be visual studio issue.

**Comment by justcla** [comment]
I use a Logitech keyboard and they shortcuts work for me. 

There might be another application on your machine that is taking control of some shortcuts. There are some Microsoft Office global shortcuts that interfere. And also Nvidia has some global shortcuts that interfere. Maybe you have Nvidia on your desktop. Check the settings and look for shortcuts.

**Comment by rainbowechoes** [comment]
I have know the reason, it's microsoft input problem. the new microsoft input will use Shift + f6 shortcuts. if you want to make the shortcuts can work, you must to open the capability mode, like this:
![image](https://github.com/user-attachments/assets/5d840667-4d4d-405d-b9f3-9a88efad0491)

this problem have existed for a long time, it's  discovered from 2023, still not fixed up to now.

after I open the capability mode, the jetbrains ide, visual studio and vs code works perfect
