### ISSUE TITLE
no support for arm64 installs

### ISSUE THREAD

**Issue by dszryan** [justcla/KeyBindings#28]

**Comment by justcla** [comment]
Are you able to submit a pull request? 
If not, I'll try to take a look soon. Thanks

**Comment by justcla** [comment]
It's easy enough to add the new "InstallationTarget" for arm64 to the source extension file.
But the extension is mostly a collection of mapping scheme files and it comes embedded with Keyboard Shortcut Manager 3.1.4, which has tools and menu items for loading keyboard mapping schemes. I think I will need to build arm64 support for that one, too, if it's going to work fully.

**Comment by justcla** [comment]
I failed my initial attempt to build the KeyboardShortcutManager with arm64 - missing references / outdated libraries :-(
This will take some more time.

**Comment by justcla** [comment]
Updated and uploaded to as v4.3.0 in Marketplace.
