### ISSUE TITLE
HoyKeys extension not installed

### ISSUE THREAD

**Issue by MaherJendoubi** [justcla/KeyBindings#3]
![image](https://cloud.githubusercontent.com/assets/1798510/22529400/97e663b6-e8d7-11e6-9d47-75ecf90284ae.png)

**Comment by justcla** [comment]
The new keyboard mapping schemes should appear under the "Keyboard" item in Tools Options.

You can check if the extension installed properly by looking for HotKeys in Tools->Extensions and Updates.
You should also find a related entry in Windows Add/Remove Programs.

**Comment by MaherJendoubi** [comment]
@justcla Thanks for the reply! I don't see it : 

![image](https://cloud.githubusercontent.com/assets/1798510/22530303/31713e5e-e8db-11e6-9fb9-39e4739d1fe6.png)

**Comment by MaherJendoubi** [comment]
@justcla I checked here but I can't find it : 

![image](https://cloud.githubusercontent.com/assets/1798510/22530362/746f53bc-e8db-11e6-9a33-563b7af25400.png)

**Comment by MaherJendoubi** [comment]
@justcla but I find it here : 
![image](https://cloud.githubusercontent.com/assets/1798510/22530434/c18a7794-e8db-11e6-962f-3a5048479cec.png)

**Comment by justcla** [comment]
As you say, it appears that HotKeys is not installed.
Did you attempt installing it?
If so, what was the result?

If it failed, can you share the error with me?

**Comment by justcla** [comment]
When you run the installer, it prompts you to select the correct directory for Visual Studio.
By default it selects the installation directory for VS2015.
If you have installed VS to a different directly, you must choose the root of installed instance.

I suggest that you uninstall it via Add/Remove programs.
Then try installing it again.
When it prompts to select the directory to install to, carefully check to make sure it's installing in the right place.

**Comment by MaherJendoubi** [comment]
@justcla Did you attempt installing it? I downloaded HotKeys-v1.2.1.msi from https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotKeys-KeyboardShortcuts

**Comment by justcla** [comment]
The installer attempts to put files into the [VSInstallRoot]\Common7\IDE directory.
And it creates an extension directory under [VSInstallRoot]\Common7\IDE\Extensions.

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/22530654/dfa27e7e-e8dc-11e6-9dfa-7397593b267b.png)

**Comment by MaherJendoubi** [comment]
@justcla is that path correct?

**Comment by justcla** [comment]
@MaherJendoubi I just installed it now and it worked for me.

**Comment by justcla** [comment]
Is that the path that you installed VS2015 to?

**Comment by MaherJendoubi** [comment]
@justcla yes

**Comment by justcla** [comment]
How many VSK files do you have in your C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE directory?
Can you see the following directory:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\KeyBindingSchemes
?

**Comment by justcla** [comment]
Also, did you restart VS? You need to restart VS for the extension to show up in the Extensions and Updtes dialog.

But the VSKs will show up in the Keyboard options page in the dropdown at the top (Keyboard mapping schemes) immediately - as soon as the VSKs get copied into the Common7\IDE directory.

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/22531258/2a75a98c-e8e0-11e6-9364-5f3f5df9af1f.png)

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/22531283/48148030-e8e0-11e6-8d33-511c0c9b42d8.png)

**Comment by MaherJendoubi** [comment]
@justcla I restarted VS many times

**Comment by justcla** [comment]
Great. The VSK files are in the right place. And the extension dir is correct.
The extension is fully installed.
:-)

Now what do you see when you open the drop-down list at the top of the Keyboard options page?

Do you see all the VSKs that are in your Common7\IDE directory?

![image](https://cloud.githubusercontent.com/assets/17131343/22531396/6d4a3eb2-e895-11e6-930a-000243557e8f.png)

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/22531511/8dc83d0a-e8e1-11e6-8aa5-7cdd152f4fe0.png)

**Comment by justcla** [comment]
I'm not sure what that last comment / image is about.
It does not show the contents of the mapping scheme drop-down.
(I use the in-built Windows "Snipping Tool" and set a delay of 5 seconds to screenshot the drop-down box values.)

Do you see the new keyboard mapping schemes in the drop-down box?

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/22531563/173559d8-e8e2-11e6-8fe0-ebe92c7ed1c3.png)

**Comment by justcla** [comment]
Bingo! The extension has installed the new keyboard mapping files and they are available for you to select from the Keyboard options page.
Congratulations.
I hope you enjoy using the new key bindings.

Out of interest, which mapping scheme are you most interested in?

**Comment by MaherJendoubi** [comment]
Out of interest, which mapping scheme are you most interested in? Resharper (VS Style) for C#

But I'm not convinced that the extension is well installed :(

**Comment by MaherJendoubi** [comment]
@justcla why I don't have a green window like you showed in channel 9 video?

**Comment by MaherJendoubi** [comment]
@justcla Why I don't see the extension in the list on installed vs extensions?

**Comment by justcla** [comment]
@MaherJendoubi The extension is installed if you have the new mapping schemes appearing in the Keyboard options.

I'm not sure why the extension is not showing up in your Extensions and Updates dialog. Sometimes the E&U is out of date. It occasionally rebuilds. If you delete all the cache files from the Common7\IDE\Extensions directory then it will re-scan the extensions directories and rebuild the list of installed extensions.

**Comment by justcla** [comment]
The only reason you saw green windows in the video is because I have set green as my Windows colour theme. If you want your windows to look green, you can adjust your colours in the Settings (Right-click desktop and choose Personalise).

![image](https://cloud.githubusercontent.com/assets/17131343/22532259/ff308c50-e89a-11e6-9f17-b505ca10e4aa.png)

**Comment by justcla** [comment]
Closing this issue since the mapping schemes have been successfully installed.

**Comment by MaherJendoubi** [comment]
@justcla I deleted extensions files... and my VS2015 is brocken now...

**Comment by MaherJendoubi** [comment]
I can't sign in and I can't create whatever new project. I reboot VS and even my machine.

**Comment by justcla** [comment]
Oh dear. :-(
You need to be careful deleting files.

**Comment by MaherJendoubi** [comment]
no problem I will repair it
