### ISSUE TITLE
Resharper (VS/IDEA  style) Alt-Enter doesn't work as intended.

### ISSUE THREAD

**Issue by mundusnine** [justcla/KeyBindings#8]
Desired: Show potential fixes.

Got: Refocuses(selects the tab like when you click on it) to the Properties tab.

**Comment by justcla** [comment]
Which version of VS are you running?
Alt+Enter defaults to Properties tab in VS2015 in some schemes.
Either way, it sounds like the ReSharper keyboard scheme isn't installed or activated properly.
What scheme is showing in Tools->Options, Keyboard?

**Comment by mundusnine** [comment]
VS 2017 - I tried both in ctrl+alt+s.  Ctrl+ R, R works so I think it works partially

**Comment by justcla** [comment]
Not necessarily. Ctrl+R, R is in the default mapping.

Question: What scheme is showing in Tools->Options, Keyboard?
In the first drop-down (Keyboard mapping scheme).

If it says "(Default)" then the scheme has not been applied, which would explain the behavior you're seeing.

**Comment by mundusnine** [comment]
I changed the key shemes to Resharper(VS style) for C# and Resharper (Idea style ) for C#.

**Comment by justcla** [comment]
I have discovered that changing the mapping scheme via the menu items on the Keyboard Shortcuts Manager does not persist across sessions. (I don't know why. The engineers I spoke to didn't know why, either.)
As such, it's best to change the mapping scheme via the regular dialog in Tools->Options;Keyboard.
